### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by 25** [25/EnchantmentsEnhance#178]
[23:41:42] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EnchantmentsEnhance v7.9.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2147) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:196) ~[?:?]
	at com.lgou2w.ldk.reflect.FuzzyReflectMatcher.result(FuzzyReflectMatcher.kt:176) ~[?:?]
	at com.lgou2w.ldk.reflect.FuzzyReflectMethodMatcher.resultAccessorAs(FuzzyReflectMethodMatcher.kt:94) ~[?:?]
	at com.lgou2w.ldk.reflect.FuzzyReflectMethodMatcher.resultAccessor(FuzzyReflectMethodMatcher.kt:81) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory$METHOD_NBT_CREATE$2.invoke(NBTFactory.kt:75) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory$METHOD_NBT_CREATE$2.invoke(NBTFactory.kt:49) ~[?:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.getMETHOD_NBT_CREATE(NBTFactory.kt) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.createInternal(NBTFactory.kt:199) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.toNMS(NBTFactory.kt:189) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.toNMS(NBTFactory.kt:172) ~[?:?]
	at com.lgou2w.ldk.bukkit.item.ItemFactory.writeTag(ItemFactory.kt:325) ~[?:?]
	at com.lgou2w.ldk.bukkit.item.ItemFactory.writeTag(ItemFactory.kt:316) ~[?:?]
	at com.lgou2w.ldk.bukkit.item.ItemFactory.modifyTag(ItemFactory.kt:352) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.modifyTagSafely(ItemManager.java:88) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.setLevel(ItemManager.java:116) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.forgeItem(ItemManager.java:187) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.forgeItemWithoutReplacement(ItemManager.java:217) ~[?:?]
	at org.pixeltime.enchantmentsenhance.gui.menu.icons.ForgedIcon.getItem(ForgedIcon.java:23) ~[?:?]
	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:238) ~[?:?]
	at org.pixeltime.enchantmentsenhance.gui.menu.handlers.MenuHandler.onClick(MenuHandler.java:40) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	... 17 more

**Comment by 25** [comment]
Caused by fixing #174

**Comment by 25** [comment]
https://github.com/25/EnchantmentsEnhance/pull/177/commits/ea69ef7fb15ee52e31e4b1e614cbe093849e1b7f#diff-a7e6c3a5f45026009dc329d19d887929L80

**Comment by 25** [comment]
https://github.com/25/EnchantmentsEnhance/pull/177/commits/ea69ef7fb15ee52e31e4b1e614cbe093849e1b7f#diff-a7e6c3a5f45026009dc329d19d887929R80-R95

**Comment by 25** [comment]
https://github.com/25/EnchantmentsEnhance/blob/ea69ef7fb15ee52e31e4b1e614cbe093849e1b7f/modules/EnchantmentsEnhance-Plugin/src/main/java/org/pixeltime/enchantmentsenhance/manager/ItemManager.java#L80

**Comment by lgou2w** [comment]
@25 See lgou2w/ldk#104 . Please update LDK to `0.2.0-SNAPSHOT`.

**Comment by lgou2w** [comment]
Or can wait for the stable version of `0.2.0`, which is expected to be released on `01/01/2020` . 😄

**Comment by 25** [comment]
https://github.com/25/EnchantmentsEnhance/commit/f43bfa91db8f8e01dd4363ffdb10de074b9ccc54

Did not solve the issue

**Comment by lgou2w** [comment]
Add sonatype snapshot repository to ensure the latest snapshot version!

```xml
<!-- if you need use snapshot version, add sonatype repo -->
<repositories>
  <repository>
    <id>sonatype-repo</id>
    <url>https://oss.sonatype.org/content/groups/public/</url>
  </repository>
</repositories>
```
E.g: https://oss.sonatype.org/content/groups/public/com/lgou2w/ldk-bukkit-nbt/0.2.0-SNAPSHOT/

![图片](https://user-images.githubusercontent.com/13819168/71574409-8dbc5080-2b23-11ea-8a4f-48f134545ef1.png)

This bug was fixed on Dec 27. Make sure that your project uses a snapshot version no less than this.

**Comment by lgou2w** [comment]
And make sure that the runtime environment of Bukkit is this version of the LDK.

**Comment by 25** [comment]
```Caused by: java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:196) ~[?:?]
	at com.lgou2w.ldk.reflect.FuzzyReflectMatcher.result(FuzzyReflectMatcher.kt:176) ~[?:?]
	at com.lgou2w.ldk.reflect.FuzzyReflectMethodMatcher.resultAccessorAs(FuzzyReflectMethodMatcher.kt:94) ~[?:?]
	at com.lgou2w.ldk.reflect.FuzzyReflectMethodMatcher.resultAccessor(FuzzyReflectMethodMatcher.kt:81) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory$METHOD_NBT_CREATE$2.invoke(NBTFactory.kt:75) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory$METHOD_NBT_CREATE$2.invoke(NBTFactory.kt:49) ~[?:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.getMETHOD_NBT_CREATE(NBTFactory.kt) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.createInternal(NBTFactory.kt:199) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.toNMS(NBTFactory.kt:189) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.toNMS(NBTFactory.kt:172) ~[?:?]
	at com.lgou2w.ldk.bukkit.item.ItemFactory.writeTag(ItemFactory.kt:325) ~[?:?]
	at com.lgou2w.ldk.bukkit.item.ItemFactory.writeTag(ItemFactory.kt:316) ~[?:?]
	at com.lgou2w.ldk.bukkit.item.ItemFactory.modifyTag(ItemFactory.kt:352) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.modifyTagSafely(ItemManager.java:88) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.setLevel(ItemManager.java:116) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.forgeItem(ItemManager.java:187) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.forgeItemWithoutReplacement(ItemManager.java:217) ~[?:?]
	at org.pixeltime.enchantmentsenhance.gui.menu.icons.ForgedIcon.getItem(ForgedIcon.java:23) ~[?:?]
	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:238) ~[?:?]
	at org.pixeltime.enchantmentsenhance.gui.menu.handlers.MenuHandler.onClick(MenuHandler.java:40) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	... 17 more
```
```
[INFO] Including com.lgou2w:ldk-chat:jar:0.2.0-SNAPSHOT in the shaded jar.
[INFO] Including com.lgou2w:ldk-bukkit-reflect:jar:0.2.0-SNAPSHOT in the shaded jar.
[INFO] Including com.lgou2w:ldk-bukkit-nbt:jar:0.2.0-SNAPSHOT in the shaded jar.
[INFO] Including com.lgou2w:ldk-nbt:jar:0.2.0-SNAPSHOT in the shaded jar.
[INFO] Including com.lgou2w:ldk-bukkit-gui:jar:0.2.0-SNAPSHOT in the shaded jar.
[INFO] Including com.lgou2w:ldk-bukkit-cmd:jar:0.2.0-SNAPSHOT in the shaded jar.
[INFO] Including com.lgou2w:ldk-bukkit-compatibility:jar:0.2.0-SNAPSHOT in the shaded jar.
```
```
[INFO] --------------------------------[ pom ]---------------------------------
Downloading from sonatype-repo: https://oss.sonatype.org/content/groups/public/com/lgou2w/ldk-reflect/0.2.0-SNAPSHOT/maven-metadata.xml
Downloaded from sonatype-repo: https://oss.sonatype.org/content/groups/public/com/lgou2w/ldk-reflect/0.2.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 5.4 kB/s)
Downloading from sonatype-repo: https://oss.sonatype.org/content/groups/public/com/lgou2w/ldk-common/0.2.0-SNAPSHOT/maven-metadata.xml
Downloaded from sonatype-repo: https://oss.sonatype.org/content/groups/public/com/lgou2w/ldk-common/0.2.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 17 kB/s)
Downloading from sonatype-repo: https://oss.sonatype.org/content/groups/public/com/lgou2w/ldk-bukkit-version/0.2.0-SNAPSHOT/maven-metadata.xml
Downloaded from sonatype-repo: https://oss.sonatype.org/content/groups/public/com/lgou2w/ldk-bukkit-version/0.2.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 21 kB/s)
Downloading from sonatype-repo: https://oss.sonatype.org/content/groups/public/com/lgou2w/ldk-bukkit/0.2.0-SNAPSHOT/maven-metadata.xml
Downloaded from sonatype-repo: https://oss.sonatype.org/content/groups/public/com/lgou2w/ldk-bukkit/0.2.0-SNAPSHOT/maven-metadata.xml (814 B at 17 kB/s)

```

**Comment by 25** [comment]
Not sure what went wrong, but it still does not work.

Have you pushed all the changes to the sonatype-repo as well?

**Comment by 25** [comment]
https://github.com/25/EnchantmentsEnhance/commit/df552a61cc5a397744357435911a5d0157576a6b

**Comment by lgou2w** [comment]
这个问题怎么说呢，应该是这个服务端里面有多个 `LDK` 环境，因为 `EE` 是 `shaded` 方式打包 `LDK` 的对吧。如果服务端包含了一个旧版本的 `LDK`，那么加载的类就是这个旧版本的。所以你先调试一下 `/pl` 看看是不是有其他的 `LDK` 环境。如果有那就检测一下 `git` 的 `commit hash id` 版本号。暂时用中文说明，英文说的不明白可能，问题先保持开启。

**Comment by 25** [comment]
我测试的时候插件列表里只有EE，/pl 里也只有EE，所以可以保证是Shaded的LDK

**Comment by 25** [comment]
Spigot 1.15
<ldk.version>0.2.0-SNAPSHOT</ldk.version>
```
[00:54:06] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EnchantmentsEnhance v7.9.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2147) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:196) ~[?:?]
	at com.lgou2w.ldk.reflect.FuzzyReflectMatcher.result(FuzzyReflectMatcher.kt:176) ~[?:?]
	at com.lgou2w.ldk.reflect.FuzzyReflectMethodMatcher.resultAccessorAs(FuzzyReflectMethodMatcher.kt:94) ~[?:?]
	at com.lgou2w.ldk.reflect.FuzzyReflectMethodMatcher.resultAccessor(FuzzyReflectMethodMatcher.kt:81) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory$METHOD_NBT_CREATE$2.invoke(NBTFactory.kt:75) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory$METHOD_NBT_CREATE$2.invoke(NBTFactory.kt:49) ~[?:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.getMETHOD_NBT_CREATE(NBTFactory.kt) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.createInternal(NBTFactory.kt:199) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.toNMS(NBTFactory.kt:189) ~[?:?]
	at com.lgou2w.ldk.bukkit.nbt.NBTFactory.toNMS(NBTFactory.kt:172) ~[?:?]
	at com.lgou2w.ldk.bukkit.item.ItemFactory.writeTag(ItemFactory.kt:325) ~[?:?]
	at com.lgou2w.ldk.bukkit.item.ItemFactory.writeTag(ItemFactory.kt:316) ~[?:?]
	at com.lgou2w.ldk.bukkit.item.ItemFactory.modifyTag(ItemFactory.kt:352) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.modifyTagSafely(ItemManager.java:88) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.setLevel(ItemManager.java:116) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.forgeItem(ItemManager.java:187) ~[?:?]
	at org.pixeltime.enchantmentsenhance.manager.ItemManager.forgeItemWithoutReplacement(ItemManager.java:217) ~[?:?]
	at org.pixeltime.enchantmentsenhance.gui.menu.icons.ForgedIcon.getItem(ForgedIcon.java:23) ~[?:?]
	at org.pixeltime.enchantmentsenhance.gui.menu.MainMenu.update(MainMenu.java:238) ~[?:?]
	at org.pixeltime.enchantmentsenhance.gui.menu.handlers.MenuHandler.onClick(MenuHandler.java:40) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
	... 17 more
```

**Comment by lgou2w** [comment]
等一下我编译一下看看

**Comment by lgou2w** [comment]
我编译测试并没有问题呢

![图片](https://user-images.githubusercontent.com/13819168/71612114-07624600-2bd9-11ea-82d8-10c2a21c892f.png)

**Comment by 25** [comment]
我试试在docker容器里构建结果会不会不同

**Comment by lgou2w** [comment]
可能你的本地 maven 仓库是还没有下载最新版的快照，你打开项目这样操作：
1. Ctrl + A 全选 Maven 项目
2. 点击 reimport all project

让 maven 触发重新导入，以下载最新的快照。

![图片](https://user-images.githubusercontent.com/13819168/71612124-2f51a980-2bd9-11ea-85dd-ee654201b85d.png)

**Comment by lgou2w** [comment]
你可以那样，你编译打包出 jar 后，用 jd-gui 反编译看一下这个路径。
是否有两个 `createInternal` 函数，最后是个 `NBTType` 类型的，那么是没问题的。

![图片](https://user-images.githubusercontent.com/13819168/71612163-763f9f00-2bd9-11ea-86a9-efbef214d8ac.png)

**Comment by lgou2w** [comment]
最终的发布版本下载链接是谁提供构建的？如果不行的话就等待明天 LDK 0.2.0 的正式版，今天是今年的最后一天了呢。🤔

**Comment by 25** [comment]
Solved!

Built the project in docker and it works. That means I had issues with local maven repositories.
